// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkle.proto

package com.woo.merkle.proto;

public interface MerkleNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:merkle.MerkleNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes hash = 1;</code>
   * @return Whether the hash field is set.
   */
  boolean hasHash();
  /**
   * <code>optional bytes hash = 1;</code>
   * @return The hash.
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <pre>
   * hash of left merkle node
   * </pre>
   *
   * <code>optional bytes left = 2;</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <pre>
   * hash of left merkle node
   * </pre>
   *
   * <code>optional bytes left = 2;</code>
   * @return The left.
   */
  com.google.protobuf.ByteString getLeft();

  /**
   * <code>optional bytes right = 3;</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <code>optional bytes right = 3;</code>
   * @return The right.
   */
  com.google.protobuf.ByteString getRight();

  /**
   * <code>optional bytes parent = 4;</code>
   * @return Whether the parent field is set.
   */
  boolean hasParent();
  /**
   * <code>optional bytes parent = 4;</code>
   * @return The parent.
   */
  com.google.protobuf.ByteString getParent();

  /**
   * <code>.merkle.MerkleBalanceVector balance = 5;</code>
   * @return Whether the balance field is set.
   */
  boolean hasBalance();
  /**
   * <code>.merkle.MerkleBalanceVector balance = 5;</code>
   * @return The balance.
   */
  MerkleBalanceVector getBalance();
  /**
   * <code>.merkle.MerkleBalanceVector balance = 5;</code>
   */
  MerkleBalanceVectorOrBuilder getBalanceOrBuilder();
}
