// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkle.proto

package com.woo.merkle.proto;

public final class Merkle {
  private Merkle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_merkle_MerkleNode_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_merkle_MerkleNode_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_merkle_MerkleBalanceVector_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_merkle_MerkleBalanceVector_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_merkle_UserHash_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_merkle_UserHash_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_merkle_MerkleTree_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_merkle_MerkleTree_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014merkle.proto\022\006merkle\"\260\001\n\nMerkleNode\022\021\n" +
      "\004hash\030\001 \001(\014H\000\210\001\001\022\021\n\004left\030\002 \001(\014H\001\210\001\001\022\022\n\005r" +
      "ight\030\003 \001(\014H\002\210\001\001\022\023\n\006parent\030\004 \001(\014H\003\210\001\001\022,\n\007" +
      "balance\030\005 \001(\0132\033.merkle.MerkleBalanceVect" +
      "orB\007\n\005_hashB\007\n\005_leftB\010\n\006_rightB\t\n\007_paren" +
      "t\"\\\n\023MerkleBalanceVector\022\r\n\005index\030\001 \003(\005\022" +
      "\020\n\010balances\030\002 \003(\t\022\026\n\tleafIdnex\030\003 \001(\005H\000\210\001" +
      "\001B\014\n\n_leafIdnex\"9\n\010UserHash\022\013\n\003uid\030\001 \001(\003" +
      "\022\r\n\005nonce\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\"?\n\nMe" +
      "rkleTree\022\016\n\006tokens\030\001 \003(\t\022!\n\005nodes\030\002 \003(\0132" +
      "\022.merkle.MerkleNodeB \n\024com.woo.merkle.pr" +
      "otoB\006MerkleP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_merkle_MerkleNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_merkle_MerkleNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_merkle_MerkleNode_descriptor,
        new String[] { "Hash", "Left", "Right", "Parent", "Balance", "Hash", "Left", "Right", "Parent", });
    internal_static_merkle_MerkleBalanceVector_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_merkle_MerkleBalanceVector_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_merkle_MerkleBalanceVector_descriptor,
        new String[] { "Index", "Balances", "LeafIdnex", "LeafIdnex", });
    internal_static_merkle_UserHash_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_merkle_UserHash_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_merkle_UserHash_descriptor,
        new String[] { "Uid", "Nonce", "Timestamp", });
    internal_static_merkle_MerkleTree_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_merkle_MerkleTree_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_merkle_MerkleTree_descriptor,
        new String[] { "Tokens", "Nodes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
