// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkle.proto

package com.woo.merkle.proto;

public interface MerkleTreeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:merkle.MerkleTree)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * token and its index
   * </pre>
   *
   * <code>repeated string tokens = 1;</code>
   * @return A list containing the tokens.
   */
  java.util.List<String>
      getTokensList();
  /**
   * <pre>
   * token and its index
   * </pre>
   *
   * <code>repeated string tokens = 1;</code>
   * @return The count of tokens.
   */
  int getTokensCount();
  /**
   * <pre>
   * token and its index
   * </pre>
   *
   * <code>repeated string tokens = 1;</code>
   * @param index The index of the element to return.
   * @return The tokens at the given index.
   */
  String getTokens(int index);
  /**
   * <pre>
   * token and its index
   * </pre>
   *
   * <code>repeated string tokens = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the tokens at the given index.
   */
  com.google.protobuf.ByteString
      getTokensBytes(int index);

  /**
   * <code>repeated .merkle.MerkleNode nodes = 2;</code>
   */
  java.util.List<MerkleNode>
      getNodesList();
  /**
   * <code>repeated .merkle.MerkleNode nodes = 2;</code>
   */
  MerkleNode getNodes(int index);
  /**
   * <code>repeated .merkle.MerkleNode nodes = 2;</code>
   */
  int getNodesCount();
  /**
   * <code>repeated .merkle.MerkleNode nodes = 2;</code>
   */
  java.util.List<? extends MerkleNodeOrBuilder>
      getNodesOrBuilderList();
  /**
   * <code>repeated .merkle.MerkleNode nodes = 2;</code>
   */
  MerkleNodeOrBuilder getNodesOrBuilder(
      int index);
}
