// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkle.proto

package com.woo.merkle.proto;

public interface MerkleBalanceVectorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:merkle.MerkleBalanceVector)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * make sure index is ascending order, so that hash always is the same
   * </pre>
   *
   * <code>repeated int32 index = 1;</code>
   * @return A list containing the index.
   */
  java.util.List<Integer> getIndexList();
  /**
   * <pre>
   * make sure index is ascending order, so that hash always is the same
   * </pre>
   *
   * <code>repeated int32 index = 1;</code>
   * @return The count of index.
   */
  int getIndexCount();
  /**
   * <pre>
   * make sure index is ascending order, so that hash always is the same
   * </pre>
   *
   * <code>repeated int32 index = 1;</code>
   * @param index The index of the element to return.
   * @return The index at the given index.
   */
  int getIndex(int index);

  /**
   * <code>repeated string balances = 2;</code>
   * @return A list containing the balances.
   */
  java.util.List<String>
      getBalancesList();
  /**
   * <code>repeated string balances = 2;</code>
   * @return The count of balances.
   */
  int getBalancesCount();
  /**
   * <code>repeated string balances = 2;</code>
   * @param index The index of the element to return.
   * @return The balances at the given index.
   */
  String getBalances(int index);
  /**
   * <code>repeated string balances = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the balances at the given index.
   */
  com.google.protobuf.ByteString
      getBalancesBytes(int index);

  /**
   * <code>optional int32 leafIdnex = 3;</code>
   * @return Whether the leafIdnex field is set.
   */
  boolean hasLeafIdnex();
  /**
   * <code>optional int32 leafIdnex = 3;</code>
   * @return The leafIdnex.
   */
  int getLeafIdnex();
}
