// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: merkle.proto

package com.woo.merkle.proto;

public interface UserHashOrBuilder extends
    // @@protoc_insertion_point(interface_extends:merkle.UserHash)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>string nonce = 2;</code>
   * @return The nonce.
   */
  String getNonce();
  /**
   * <code>string nonce = 2;</code>
   * @return The bytes for nonce.
   */
  com.google.protobuf.ByteString
      getNonceBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
